PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/03d461f7e2815f87b38eb847f399418b71730084

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/904a602c74dc08a100b5c2bd490807de19e73e10) in current PX4/master (bd09be43c0962f52053e59a4bc311c753bf83805)
https://github.com/PX4/NuttX/compare/904a602c74dc08a100b5c2bd490807de19e73e10...03d461f7e2815f87b38eb847f399418b71730084

03d461f7e2 (HEAD, origin/master) tools: Add 'handle SIGUSR1' to nuttx-gdbinit for the NuttX sim SMP
bcdee59929 arch/stm32: Fix nxstyle errors
d6c24312aa Fix nxstyle warning
afb0e33138 libc/machine/arch: Support armv8-m relocation
74ab69af62 libs/libc/machine/arm: Rename armv8 to armv8-m
edca49fb5f libc/machine/arm: Use the correct arch Kconfig for variant check
baabe5e08a libs/libc/machine: Remove ARCH_CORTEXM33 dependence from LIBM_ARCH_xxx
a59c7744f8 Documentation: support versioned docs
36088e8d21 Config.mk: fix CATFILE macro to work when file list is empty (Linux)
b021375f2c Update checkrelease script for readme.md inread of .txt

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/0eac03524508fd9bf068ffc8ba9c1e9eff5c66c3

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/909eff540d8004371d5838b9c0764cc753d665cf) in current PX4/master (bd09be43c0962f52053e59a4bc311c753bf83805)
https://github.com/PX4/NuttX-apps/compare/909eff540d8004371d5838b9c0764cc753d665cf...0eac03524508fd9bf068ffc8ba9c1e9eff5c66c3

0eac0352 (HEAD -> master, origin/master) examples/cctye: change std::isascii to isascii
72d9b34f netutils/tftpc/tftpc_put.c: Fix syslog formats
5a4bf6b3 netutils/tftpc/tftpc_get.c: Fix a syslog format
eeded9da netutils/ntpclient/ntpclient.c: Fix syslog formats
13424fc4 netutils/ftpc/ftpc_putfile.c: Fix syslog formats
2a3f2ea8 netutils/ftpc/ftpc_putfile.c: Appease nxstyle
7b3ccfa9 netutils/ftpc/ftpc_getfile.c: Fix a syslog format
f83caca9 netutils/ftpc/ftpc_getfile.c: Appease nxstyle
24b6f919 examples/mld: Fix undefined reference to `mld_catfile'
a4ae1592 examples/i2schar: Fix the compile error